### ISSUE TITLE
Issue when trying to upgrade when modularflightintegrator is not removed prior.

### ISSUE THREAD

**Issue by vinix38** [R-T-B/CKAN-meta-dev-Kopernicus_BE#2]
KSP version: 1.11.0

Most recent versions of kopernicus BE are marked as conflicting with modularflightintegrator. 
Therefore, if you remove Kopernicus BE (BUT not modularflightintegrator) and try to install it again, only kopernicus BE for KSP 1.10.1 will be marked as compatible. CKAN will refuse to install any KBE for 1.11.0, because of the conflict.
I had to manually remove modularflightintegrator before installing again.
I guess there is a good reason for that, as I have seen modularflightintegrator related changes in recent changelogs.
My issue might result from a weird combination of auto and manually installed versions, and as a result may be irrelevant, but I wanted to report it anyway in case there is anything to change/improve

Picture (probably useless):
![image](https://user-images.githubusercontent.com/68441743/105890919-40edc680-6010-11eb-8f3c-7b0187a98f74.png)

**Comment by R-T-B** [comment]
Thanks.  The truth is rather boring unfornuntately.  The only reason 1.11 builds are like that is because of this issue:

https://github.com/sarbian/ModularFlightIntegrator/issues/13

We are waiting on @sarbian to act, essentially.  I'm sure he will when he gets time.  If you have a better idea of a way to handle this, do let me know.  We are actually shipping mainline MFI.

**Comment by R-T-B** [comment]
Sarbian has acted, and next release will revert 1.11 builds to a normal dependency structure.

**Comment by R-T-B** [comment]
Closing as resolved.
